from datetime import datetime
from pathlib import Path
from types import TracebackType
from typing import Protocol, Self
from uuid import UUID

from crucible.application.idempotency import IdempotencyRecord
from crucible.context.manifests import ContextManifest
from crucible.domain.approvals import Approval
from crucible.domain.artifacts import Artifact
from crucible.domain.conversation import Message
from crucible.domain.events import Event
from crucible.domain.repository import Repository
from crucible.domain.resources import ExternalResource
from crucible.domain.run import Run
from crucible.domain.steps import Step
from crucible.domain.task import Task
from crucible.domain.tools import ToolCall, ToolResult


class RepositoryStore(Protocol):
    async def add_if_absent(self, repository: Repository) -> bool: ...
    async def get_by_root(self, root: Path) -> Repository | None: ...
    async def list(self) -> tuple[Repository, ...]: ...
    async def get(self, repository_id: UUID) -> Repository | None: ...


class TaskStore(Protocol):
    async def add(self, task: Task) -> None: ...
    async def get(self, task_id: UUID) -> Task | None: ...
    async def update(self, task: Task) -> None: ...
    async def list_provisioning(self) -> tuple[Task, ...]: ...


class MessageStore(Protocol):
    async def add(self, message: Message) -> Message: ...
    async def list_for_task(self, task_id: UUID) -> tuple[Message, ...]: ...


class StepStore(Protocol):
    async def add(self, step: Step) -> None: ...
    async def update(self, step: Step) -> None: ...
    async def list_for_run(self, run_id: UUID) -> tuple[Step, ...]: ...


class ContextManifestStore(Protocol):
    async def add(self, manifest: ContextManifest) -> None: ...
    async def get_for_step(self, step_id: UUID) -> ContextManifest | None: ...


class ToolCallStore(Protocol):
    async def add(self, call: ToolCall) -> None: ...
    async def update(self, call: ToolCall) -> None: ...
    async def list_for_step(self, step_id: UUID) -> tuple[ToolCall, ...]: ...
    async def list_without_result_for_run(
        self, run_id: UUID
    ) -> tuple[ToolCall, ...]: ...


class ToolResultStore(Protocol):
    async def add(self, result: ToolResult) -> None: ...
    async def list_for_step(self, step_id: UUID) -> tuple[ToolResult, ...]: ...


class ApprovalStore(Protocol):
    async def add(self, approval: Approval) -> None: ...
    async def get(self, approval_id: UUID) -> Approval | None: ...
    async def get_for_tool_call(self, tool_call_id: UUID) -> Approval | None: ...
    async def update(self, approval: Approval) -> None: ...
    async def decide_pending(self, approval: Approval) -> bool: ...
    async def list_for_task(self, task_id: UUID) -> tuple[Approval, ...]: ...
    async def list_pending_for_run(self, run_id: UUID) -> tuple[Approval, ...]: ...
    async def list_for_run(self, run_id: UUID) -> tuple[Approval, ...]: ...


class ArtifactMetadataStore(Protocol):
    async def add(self, artifact: Artifact) -> None: ...
    async def get(self, artifact_id: UUID) -> Artifact | None: ...
    async def get_by_content(
        self,
        task_id: UUID,
        content_hash: str,
        media_type: str,
        sensitivity: str,
    ) -> Artifact | None: ...


class ExternalResourceStore(Protocol):
    async def add(self, resource: ExternalResource) -> None: ...
    async def get(self, resource_id: UUID) -> ExternalResource | None: ...
    async def update(self, resource: ExternalResource) -> None: ...
    async def list_for_task(self, task_id: UUID) -> tuple[ExternalResource, ...]: ...
    async def list_managed(self) -> tuple[ExternalResource, ...]: ...


class RunStore(Protocol):
    async def add(self, run: Run) -> None: ...
    async def get(self, run_id: UUID) -> Run | None: ...
    async def update(self, run: Run) -> None: ...
    async def list_queued(self) -> tuple[Run, ...]: ...
    async def list_running(self) -> tuple[Run, ...]: ...
    async def list_for_task(self, task_id: UUID) -> tuple[Run, ...]: ...
    async def list_running_not_owned_by(
        self, process_execution_id: UUID
    ) -> tuple[Run, ...]: ...
    async def claim_queued(
        self,
        run_id: UUID,
        execution_id: UUID,
        now: datetime,
        lease_expires_at: datetime,
    ) -> bool: ...
    async def set_triggering_message(self, run_id: UUID, message_id: UUID) -> None: ...


class EventStore(Protocol):
    async def append(self, event: Event) -> Event: ...
    async def get(self, event_id: UUID) -> Event | None: ...
    async def list_after(
        self, task_id: UUID, sequence: int, limit: int = 100
    ) -> tuple[Event, ...]: ...


class IdempotencyStore(Protocol):
    async def add(self, record: IdempotencyRecord) -> None: ...
    async def get(self, scope: str, key: str) -> IdempotencyRecord | None: ...


class RunSupervisor(Protocol):
    async def submit(self, run_id: UUID) -> None: ...
    async def reconcile(self) -> None: ...
    async def cancel(self, run_id: UUID) -> None: ...


class EventNotifier(Protocol):
    async def notify(self, task_id: UUID) -> None: ...


class UnitOfWork(Protocol):
    repositories: RepositoryStore
    tasks: TaskStore
    messages: MessageStore
    steps: StepStore
    context_manifests: ContextManifestStore
    tool_calls: ToolCallStore
    tool_results: ToolResultStore
    approvals: ApprovalStore
    artifacts: ArtifactMetadataStore
    external_resources: ExternalResourceStore
    runs: RunStore
    events: EventStore
    idempotency: IdempotencyStore

    async def __aenter__(self) -> Self: ...
    async def __aexit__(
        self,
        exc_type: type[BaseException] | None,
        exc: BaseException | None,
        traceback: TracebackType | None,
    ) -> None: ...
    async def commit(self) -> None: ...
    async def rollback(self) -> None: ...
