from datetime import datetime
from pathlib import Path
from types import TracebackType
from typing import Protocol, Self
from uuid import UUID

from crucible.application.idempotency import IdempotencyRecord
from crucible.context.manifests import ContextManifest
from crucible.domain.approvals import Approval
from crucible.domain.artifacts import Artifact
from crucible.domain.auth import BrowserSession
from crucible.domain.compaction import Compaction
from crucible.domain.conversation import Message
from crucible.domain.evals import (
    EvalCase,
    EvalResult,
    EvalSuite,
    EvalTrial,
    RunSummary,
    StepUsage,
)
from crucible.domain.events import Event
from crucible.domain.repository import Repository
from crucible.domain.resources import ExternalResource
from crucible.domain.results import Integration, ResultRevision
from crucible.domain.run import Run
from crucible.domain.steps import Step
from crucible.domain.task import Task
from crucible.domain.tools import ToolCall, ToolResult
from crucible.domain.validation import (
    CompletionProposal,
    ValidationAttempt,
    ValidationCommandResult,
)


class RepositoryStore(Protocol):
    async def add_if_absent(self, repository: Repository) -> bool: ...
    async def get_by_root(self, root: Path) -> Repository | None: ...
    async def list(self) -> tuple[Repository, ...]: ...
    async def get(self, repository_id: UUID) -> Repository | None: ...
    async def update(self, repository: Repository) -> None: ...


class TaskStore(Protocol):
    async def add(self, task: Task) -> None: ...
    async def get(self, task_id: UUID) -> Task | None: ...
    async def update(self, task: Task) -> None: ...
    async def list_provisioning(self) -> tuple[Task, ...]: ...


class MessageStore(Protocol):
    async def add(self, message: Message) -> Message: ...
    async def get(self, message_id: UUID) -> Message | None: ...
    async def list_for_task(self, task_id: UUID) -> tuple[Message, ...]: ...


class StepStore(Protocol):
    async def add(self, step: Step) -> None: ...
    async def update(self, step: Step) -> None: ...
    async def list_for_run(self, run_id: UUID) -> tuple[Step, ...]: ...


class ContextManifestStore(Protocol):
    async def add(self, manifest: ContextManifest) -> None: ...
    async def get_for_step(self, step_id: UUID) -> ContextManifest | None: ...


class ToolCallStore(Protocol):
    async def add(self, call: ToolCall) -> None: ...
    async def update(self, call: ToolCall) -> None: ...
    async def list_for_step(self, step_id: UUID) -> tuple[ToolCall, ...]: ...
    async def list_without_result_for_run(
        self, run_id: UUID
    ) -> tuple[ToolCall, ...]: ...


class ToolResultStore(Protocol):
    async def add(self, result: ToolResult) -> None: ...
    async def list_for_step(self, step_id: UUID) -> tuple[ToolResult, ...]: ...


class ApprovalStore(Protocol):
    async def add(self, approval: Approval) -> None: ...
    async def get(self, approval_id: UUID) -> Approval | None: ...
    async def get_for_tool_call(self, tool_call_id: UUID) -> Approval | None: ...
    async def update(self, approval: Approval) -> None: ...
    async def decide_pending(self, approval: Approval) -> bool: ...
    async def list_for_task(self, task_id: UUID) -> tuple[Approval, ...]: ...
    async def list_pending_for_run(self, run_id: UUID) -> tuple[Approval, ...]: ...
    async def list_for_run(self, run_id: UUID) -> tuple[Approval, ...]: ...


class ArtifactMetadataStore(Protocol):
    async def add(self, artifact: Artifact) -> None: ...
    async def get(self, artifact_id: UUID) -> Artifact | None: ...
    async def get_by_content(
        self,
        task_id: UUID,
        content_hash: str,
        media_type: str,
        sensitivity: str,
    ) -> Artifact | None: ...


class ExternalResourceStore(Protocol):
    async def add(self, resource: ExternalResource) -> None: ...
    async def get(self, resource_id: UUID) -> ExternalResource | None: ...
    async def update(self, resource: ExternalResource) -> None: ...
    async def list_for_task(self, task_id: UUID) -> tuple[ExternalResource, ...]: ...
    async def list_managed(self) -> tuple[ExternalResource, ...]: ...


class RunStore(Protocol):
    async def add(self, run: Run) -> None: ...
    async def get(self, run_id: UUID) -> Run | None: ...
    async def update(self, run: Run) -> None: ...
    async def list_queued(self) -> tuple[Run, ...]: ...
    async def list_running(self) -> tuple[Run, ...]: ...
    async def list_for_task(self, task_id: UUID) -> tuple[Run, ...]: ...
    async def get_nonterminal_for_task(self, task_id: UUID) -> Run | None: ...
    async def list_running_not_owned_by(
        self, process_execution_id: UUID
    ) -> tuple[Run, ...]: ...
    async def claim_queued(
        self,
        run_id: UUID,
        execution_id: UUID,
        now: datetime,
        lease_expires_at: datetime,
    ) -> bool: ...
    async def set_triggering_message(self, run_id: UUID, message_id: UUID) -> None: ...


class EventStore(Protocol):
    async def append(self, event: Event) -> Event: ...
    async def get(self, event_id: UUID) -> Event | None: ...
    async def list_after(
        self, task_id: UUID, sequence: int, limit: int = 100
    ) -> tuple[Event, ...]: ...


class IdempotencyStore(Protocol):
    async def add(self, record: IdempotencyRecord) -> None: ...
    async def get(self, scope: str, key: str) -> IdempotencyRecord | None: ...


class CompactionStore(Protocol):
    async def add(self, value: Compaction) -> None: ...
    async def get(self, value_id: UUID) -> Compaction | None: ...
    async def latest_for_task(self, task_id: UUID) -> Compaction | None: ...


class ValidationAttemptStore(Protocol):
    async def add(self, value: ValidationAttempt) -> None: ...
    async def get(self, value_id: UUID) -> ValidationAttempt | None: ...
    async def update(self, value: ValidationAttempt) -> None: ...
    async def list_for_run(self, run_id: UUID) -> tuple[ValidationAttempt, ...]: ...


class ValidationCommandResultStore(Protocol):
    async def add(self, value: ValidationCommandResult) -> None: ...
    async def list_for_attempt(
        self, attempt_id: UUID
    ) -> tuple[ValidationCommandResult, ...]: ...


class CompletionProposalStore(Protocol):
    async def add(self, value: CompletionProposal) -> None: ...
    async def update(self, value: CompletionProposal) -> None: ...
    async def get_for_run(self, run_id: UUID) -> CompletionProposal | None: ...


class ResultRevisionStore(Protocol):
    async def add(self, value: ResultRevision) -> None: ...
    async def get(self, value_id: UUID) -> ResultRevision | None: ...
    async def list_for_task(self, task_id: UUID) -> tuple[ResultRevision, ...]: ...


class IntegrationStore(Protocol):
    async def add(self, value: Integration) -> None: ...
    async def get(self, value_id: UUID) -> Integration | None: ...
    async def update(self, value: Integration) -> None: ...
    async def get_by_key(
        self, result_revision_id: UUID, key: str
    ) -> Integration | None: ...
    async def list_for_result(
        self, result_revision_id: UUID
    ) -> tuple[Integration, ...]: ...


class BrowserSessionStore(Protocol):
    async def add(self, value: BrowserSession) -> None: ...
    async def get(self, session_hash: str) -> BrowserSession | None: ...
    async def update(self, value: BrowserSession) -> None: ...


class EvalStore(Protocol):
    async def add_suite(self, value: EvalSuite) -> None: ...
    async def get_suite(
        self, partition: str, name: str, digest: str
    ) -> EvalSuite | None: ...
    async def add_case(self, value: EvalCase) -> None: ...
    async def get_case(
        self, suite_id: UUID, name: str, digest: str
    ) -> EvalCase | None: ...
    async def add_trial(self, value: EvalTrial) -> None: ...
    async def get_trial(self, trial_id: UUID) -> EvalTrial | None: ...
    async def update_trial(self, value: EvalTrial) -> None: ...
    async def add_result(self, value: EvalResult) -> None: ...
    async def get_result(self, trial_id: UUID) -> EvalResult | None: ...
    async def list_trials(self, invocation_id: UUID) -> tuple[EvalTrial, ...]: ...
    async def add_usage(self, value: StepUsage) -> None: ...
    async def upsert_summary(self, value: RunSummary) -> None: ...
    async def get_summary(self, run_id: UUID) -> RunSummary | None: ...
    async def rebuild_summary(self, run_id: UUID, now: datetime) -> RunSummary: ...


class RunSupervisor(Protocol):
    async def submit(self, run_id: UUID) -> None: ...
    async def reconcile(self) -> None: ...
    async def cancel(self, run_id: UUID) -> None: ...


class EventNotifier(Protocol):
    async def notify(self, task_id: UUID) -> None: ...


class UnitOfWork(Protocol):
    evals: EvalStore
    repositories: RepositoryStore
    tasks: TaskStore
    messages: MessageStore
    steps: StepStore
    context_manifests: ContextManifestStore
    tool_calls: ToolCallStore
    tool_results: ToolResultStore
    approvals: ApprovalStore
    artifacts: ArtifactMetadataStore
    external_resources: ExternalResourceStore
    runs: RunStore
    events: EventStore
    idempotency: IdempotencyStore
    compactions: CompactionStore
    validation_attempts: ValidationAttemptStore
    validation_command_results: ValidationCommandResultStore
    completion_proposals: CompletionProposalStore
    result_revisions: ResultRevisionStore
    integrations: IntegrationStore
    browser_sessions: BrowserSessionStore

    async def __aenter__(self) -> Self: ...
    async def __aexit__(
        self,
        exc_type: type[BaseException] | None,
        exc: BaseException | None,
        traceback: TracebackType | None,
    ) -> None: ...
    async def commit(self) -> None: ...
    async def rollback(self) -> None: ...
