from datetime import datetime
from pathlib import Path
from types import TracebackType
from typing import Protocol, Self
from uuid import UUID

from crucible.application.idempotency import IdempotencyRecord
from crucible.domain.conversation import Message
from crucible.domain.events import Event
from crucible.domain.repository import Repository
from crucible.domain.run import Run
from crucible.domain.task import Task


class RepositoryStore(Protocol):
    async def add_if_absent(self, repository: Repository) -> bool: ...
    async def get_by_root(self, root: Path) -> Repository | None: ...
    async def list(self) -> tuple[Repository, ...]: ...
    async def get(self, repository_id: UUID) -> Repository | None: ...


class TaskStore(Protocol):
    async def add(self, task: Task) -> None: ...
    async def get(self, task_id: UUID) -> Task | None: ...
    async def update(self, task: Task) -> None: ...


class MessageStore(Protocol):
    async def add(self, message: Message) -> Message: ...
    async def list_for_task(self, task_id: UUID) -> tuple[Message, ...]: ...


class RunStore(Protocol):
    async def add(self, run: Run) -> None: ...
    async def get(self, run_id: UUID) -> Run | None: ...
    async def update(self, run: Run) -> None: ...
    async def list_queued(self) -> tuple[Run, ...]: ...
    async def list_stale_running(self, now: datetime) -> tuple[Run, ...]: ...
    async def claim_queued(
        self,
        run_id: UUID,
        execution_id: UUID,
        now: datetime,
        lease_expires_at: datetime,
    ) -> bool: ...
    async def set_triggering_message(self, run_id: UUID, message_id: UUID) -> None: ...


class EventStore(Protocol):
    async def append(self, event: Event) -> Event: ...
    async def get(self, event_id: UUID) -> Event | None: ...
    async def list_after(
        self, task_id: UUID, sequence: int, limit: int = 100
    ) -> tuple[Event, ...]: ...


class IdempotencyStore(Protocol):
    async def add(self, record: IdempotencyRecord) -> None: ...
    async def get(self, scope: str, key: str) -> IdempotencyRecord | None: ...


class RunSupervisor(Protocol):
    async def submit(self, run_id: UUID) -> None: ...
    async def reconcile(self) -> None: ...


class EventNotifier(Protocol):
    async def notify(self, task_id: UUID) -> None: ...


class UnitOfWork(Protocol):
    repositories: RepositoryStore
    tasks: TaskStore
    messages: MessageStore
    runs: RunStore
    events: EventStore
    idempotency: IdempotencyStore

    async def __aenter__(self) -> Self: ...
    async def __aexit__(
        self,
        exc_type: type[BaseException] | None,
        exc: BaseException | None,
        traceback: TracebackType | None,
    ) -> None: ...
    async def commit(self) -> None: ...
    async def rollback(self) -> None: ...
