/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/repositories": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Repositories */
        get: operations["list_repositories_api_repositories_get"];
        put?: never;
        /** Register Repository */
        post: operations["register_repository_api_repositories_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/repositories/{repository_id}/tasks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Task */
        post: operations["create_task_api_repositories__repository_id__tasks_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tasks/{task_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Task */
        get: operations["get_task_api_tasks__task_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tasks/{task_id}/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Event Stream */
        get: operations["event_stream_api_tasks__task_id__events_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tasks/{task_id}/messages": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Messages */
        get: operations["list_messages_api_tasks__task_id__messages_get"];
        put?: never;
        /** Submit Message */
        post: operations["submit_message_api_tasks__task_id__messages_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tasks/{task_id}/trace": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Task Trace */
        get: operations["get_task_trace_api_tasks__task_id__trace_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tasks/{task_id}/workspace": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Workspace State */
        get: operations["get_workspace_state_api_tasks__task_id__workspace_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** ContextManifestSummary */
        ContextManifestSummary: {
            /** Estimatedtokens */
            estimatedTokens: number;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Instructiondigests */
            instructionDigests: {
                [key: string]: string;
            };
            /** Model */
            model: string;
            /** Toolschemadigest */
            toolSchemaDigest: string;
        };
        /** CreateTaskRequest */
        CreateTaskRequest: {
            /**
             * Sourceref
             * @default HEAD
             */
            sourceRef: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** MessagePartResponse */
        MessagePartResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Kind */
            kind: string;
            /** Partsequence */
            partSequence: number;
            /** Reasoningcontent */
            reasoningContent: string | null;
            /** Textcontent */
            textContent: string | null;
            /** Toolcallid */
            toolCallId: string | null;
            /** Toolresultid */
            toolResultId: string | null;
        };
        /** MessageResponse */
        MessageResponse: {
            /**
             * Completedat
             * Format: date-time
             */
            completedAt: string;
            /** Conversationsequence */
            conversationSequence: number;
            /**
             * Createdat
             * Format: date-time
             */
            createdAt: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Parts */
            parts: components["schemas"]["MessagePartResponse"][];
            /** Role */
            role: string;
            /** Runid */
            runId: string | null;
            /** Status */
            status: string;
            /** Stepid */
            stepId: string | null;
            /**
             * Taskid
             * Format: uuid
             */
            taskId: string;
        };
        /** RegisterRepositoryRequest */
        RegisterRepositoryRequest: {
            /** Path */
            path: string;
        };
        /** RepositoryResponse */
        RepositoryResponse: {
            /**
             * Createdat
             * Format: date-time
             */
            createdAt: string;
            /** Headrevision */
            headRevision: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Rootpath */
            rootPath: string;
        };
        /** StepTraceResponse */
        StepTraceResponse: {
            /** Calls */
            calls: components["schemas"]["ToolCallResponse"][];
            /**
             * Id
             * Format: uuid
             */
            id: string;
            manifest: components["schemas"]["ContextManifestSummary"] | null;
            /** Results */
            results: components["schemas"]["ToolResultResponse"][];
            /**
             * Runid
             * Format: uuid
             */
            runId: string;
            /** Status */
            status: string;
            /** Stepsequence */
            stepSequence: number;
        };
        /** SubmitMessageRequest */
        SubmitMessageRequest: {
            /** Text */
            text: string;
        };
        /** SubmittedRunResponse */
        SubmittedRunResponse: {
            /**
             * Messageid
             * Format: uuid
             */
            messageId: string;
            /**
             * Runid
             * Format: uuid
             */
            runId: string;
            /** Runstatus */
            runStatus: string;
        };
        /** TaskEventEnvelope */
        TaskEventEnvelope: {
            /**
             * Createdat
             * Format: date-time
             */
            createdAt: string;
            /**
             * Eventid
             * Format: uuid
             */
            eventId: string;
            /** Payload */
            payload: {
                [key: string]: unknown;
            };
            /** Runid */
            runId: string | null;
            /** Runsequence */
            runSequence: number | null;
            /** Schemaversion */
            schemaVersion: number;
            /**
             * Taskid
             * Format: uuid
             */
            taskId: string;
            /** Tasksequence */
            taskSequence: number;
            /** Type */
            type: string;
        };
        /** TaskResponse */
        TaskResponse: {
            /** Baserevision */
            baseRevision: string | null;
            /**
             * Createdat
             * Format: date-time
             */
            createdAt: string;
            /** Failurecode */
            failureCode: string | null;
            /** Failuredetail */
            failureDetail: string | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Repositoryid
             * Format: uuid
             */
            repositoryId: string;
            /** Sourceref */
            sourceRef: string;
            /** Status */
            status: string;
            /**
             * Updatedat
             * Format: date-time
             */
            updatedAt: string;
            /** Workspacepath */
            workspacePath: string;
        };
        /** ToolCallResponse */
        ToolCallResponse: {
            /** Arguments */
            arguments: {
                [key: string]: unknown;
            };
            /** Callsequence */
            callSequence: number;
            /** Executionmode */
            executionMode: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
            /** Status */
            status: string;
        };
        /** ToolResultResponse */
        ToolResultResponse: {
            /** Completionsequence */
            completionSequence: number;
            /** Displaytext */
            displayText: string;
            /** Errorcode */
            errorCode: string | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Result */
            result: {
                [key: string]: unknown;
            };
            /** Status */
            status: string;
            /**
             * Toolcallid
             * Format: uuid
             */
            toolCallId: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /** WorkspaceStateResponse */
        WorkspaceStateResponse: {
            /** Diff */
            diff: string;
            /** Difftruncated */
            diffTruncated: boolean;
            /** Status */
            status: string;
            /** Statustruncated */
            statusTruncated: boolean;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    list_repositories_api_repositories_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RepositoryResponse"][];
                };
            };
        };
    };
    register_repository_api_repositories_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterRepositoryRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RepositoryResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_task_api_repositories__repository_id__tasks_post: {
        parameters: {
            query?: never;
            header?: {
                "Idempotency-Key"?: string | null;
            };
            path: {
                repository_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateTaskRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_task_api_tasks__task_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                task_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    event_stream_api_tasks__task_id__events_get: {
        parameters: {
            query?: never;
            header?: {
                "Last-Event-ID"?: string | null;
            };
            path: {
                task_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_messages_api_tasks__task_id__messages_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                task_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MessageResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    submit_message_api_tasks__task_id__messages_post: {
        parameters: {
            query?: never;
            header?: {
                "Idempotency-Key"?: string | null;
            };
            path: {
                task_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SubmitMessageRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SubmittedRunResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_task_trace_api_tasks__task_id__trace_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                task_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StepTraceResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_workspace_state_api_tasks__task_id__workspace_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                task_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkspaceStateResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
