/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/approvals/{approval_id}/decision": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Decide Approval */
        post: operations["decide_approval_api_approvals__approval_id__decision_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/artifacts/{artifact_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Artifact */
        get: operations["get_artifact_api_artifacts__artifact_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/bootstrap": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Bootstrap */
        post: operations["bootstrap_api_auth_bootstrap_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Logout */
        post: operations["logout_api_auth_logout_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/session": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Resume Session */
        post: operations["resume_session_api_auth_session_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/repositories": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Repositories */
        get: operations["list_repositories_api_repositories_get"];
        put?: never;
        /** Register Repository */
        post: operations["register_repository_api_repositories_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/repositories/{repository_id}/settings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Update Repository Settings */
        put: operations["update_repository_settings_api_repositories__repository_id__settings_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/repositories/{repository_id}/target": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Repository Target */
        get: operations["get_repository_target_api_repositories__repository_id__target_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/repositories/{repository_id}/tasks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Task */
        post: operations["create_task_api_repositories__repository_id__tasks_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/result-revisions/{result_revision_id}/integrations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Integrate Result */
        post: operations["integrate_result_api_result_revisions__result_revision_id__integrations_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs/{run_id}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Cancel Run */
        post: operations["cancel_run_api_runs__run_id__cancel_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tasks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Tasks */
        get: operations["list_tasks_api_tasks_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tasks/{task_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Task */
        get: operations["get_task_api_tasks__task_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tasks/{task_id}/acceptances": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Accept Task */
        post: operations["accept_task_api_tasks__task_id__acceptances_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tasks/{task_id}/approvals": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Approvals */
        get: operations["list_approvals_api_tasks__task_id__approvals_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tasks/{task_id}/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Event Stream */
        get: operations["event_stream_api_tasks__task_id__events_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tasks/{task_id}/messages": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Messages */
        get: operations["list_messages_api_tasks__task_id__messages_get"];
        put?: never;
        /** Submit Message */
        post: operations["submit_message_api_tasks__task_id__messages_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tasks/{task_id}/review": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Task Review */
        get: operations["get_task_review_api_tasks__task_id__review_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tasks/{task_id}/trace": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Task Trace */
        get: operations["get_task_trace_api_tasks__task_id__trace_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tasks/{task_id}/workspace": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Workspace State */
        get: operations["get_workspace_state_api_tasks__task_id__workspace_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** ApprovalCommandSpecResponse */
        ApprovalCommandSpecResponse: {
            /** Arguments */
            arguments: string[];
            /** Cwd */
            cwd: string;
            /** Environmentnames */
            environmentNames: string[];
            /** Executable */
            executable: string;
            /** Image */
            image: string;
            limits: components["schemas"]["CommandLimitsResponse"];
            /** Network */
            network: string;
            /** Reason */
            reason: string;
            /** Timeoutseconds */
            timeoutSeconds: number;
        };
        /** ApprovalDecisionRequest */
        ApprovalDecisionRequest: {
            /**
             * Decision
             * @enum {string}
             */
            decision: "approved" | "denied";
            /** Reason */
            reason?: string | null;
            /** Specdigest */
            specDigest: string;
        };
        /** ApprovalResponse */
        ApprovalResponse: {
            /**
             * Createdat
             * Format: date-time
             */
            createdAt: string;
            /** Decidedat */
            decidedAt: string | null;
            /** Decidedby */
            decidedBy: string | null;
            /** Decisionreason */
            decisionReason: string | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Runid
             * Format: uuid
             */
            runId: string;
            spec: components["schemas"]["ApprovalCommandSpecResponse"];
            /** Specdigest */
            specDigest: string;
            /** Status */
            status: string;
            /**
             * Stepid
             * Format: uuid
             */
            stepId: string;
            /**
             * Taskid
             * Format: uuid
             */
            taskId: string;
            /**
             * Toolcallid
             * Format: uuid
             */
            toolCallId: string;
        };
        /** BootstrapRequest */
        BootstrapRequest: {
            /** Secret */
            secret: string;
        };
        /** BootstrapResponse */
        BootstrapResponse: {
            /** Csrftoken */
            csrfToken: string;
        };
        /** CancelledRunResponse */
        CancelledRunResponse: {
            /** Cancelrequestedat */
            cancelRequestedAt: string | null;
            /** Outcomecode */
            outcomeCode: string | null;
            /**
             * Runid
             * Format: uuid
             */
            runId: string;
            /** Status */
            status: string;
        };
        /** CommandLimitsResponse */
        CommandLimitsResponse: {
            /** Cpus */
            cpus: number;
            /** Memorybytes */
            memoryBytes: number;
            /** Outputbytes */
            outputBytes: number;
            /** Pids */
            pids: number;
        };
        /** CommandLimitsSettings */
        CommandLimitsSettings: {
            /** Cpus */
            cpus: number;
            /** Memorybytes */
            memoryBytes: number;
            /** Outputbytes */
            outputBytes: number;
            /** Pids */
            pids: number;
        };
        /** ContextManifestSummary */
        ContextManifestSummary: {
            /** Estimatedtokens */
            estimatedTokens: number;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Instructiondigests */
            instructionDigests: {
                [key: string]: string;
            };
            /** Model */
            model: string;
            /** Toolschemadigest */
            toolSchemaDigest: string;
        };
        /** CreateTaskRequest */
        CreateTaskRequest: {
            /**
             * Sourceref
             * @default HEAD
             */
            sourceRef: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** IntegrationResponse */
        IntegrationResponse: {
            /** Completedat */
            completedAt: string | null;
            /**
             * Createdat
             * Format: date-time
             */
            createdAt: string;
            /** Expectedtargetrevision */
            expectedTargetRevision: string;
            /** Failurecode */
            failureCode: string | null;
            /** Failuredetail */
            failureDetail: string | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Observedafterrevision */
            observedAfterRevision: string | null;
            /** Observedbeforerevision */
            observedBeforeRevision: string | null;
            /**
             * Repositoryid
             * Format: uuid
             */
            repositoryId: string;
            /**
             * Resultrevisionid
             * Format: uuid
             */
            resultRevisionId: string;
            /** Status */
            status: string;
            /** Targetref */
            targetRef: string;
        };
        /** IntegrationTargetRequest */
        IntegrationTargetRequest: {
            /** Expectedrevision */
            expectedRevision: string;
            /**
             * Repositoryid
             * Format: uuid
             */
            repositoryId: string;
            /** Targetref */
            targetRef: string;
        };
        /** MessagePartResponse */
        MessagePartResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Kind */
            kind: string;
            /** Partsequence */
            partSequence: number;
            /** Reasoningcontent */
            reasoningContent: string | null;
            /** Textcontent */
            textContent: string | null;
            /** Toolcallid */
            toolCallId: string | null;
            /** Toolresultid */
            toolResultId: string | null;
        };
        /** MessageResponse */
        MessageResponse: {
            /**
             * Completedat
             * Format: date-time
             */
            completedAt: string;
            /** Conversationsequence */
            conversationSequence: number;
            /**
             * Createdat
             * Format: date-time
             */
            createdAt: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Parts */
            parts: components["schemas"]["MessagePartResponse"][];
            /** Role */
            role: string;
            /** Runid */
            runId: string | null;
            /** Status */
            status: string;
            /** Stepid */
            stepId: string | null;
            /**
             * Taskid
             * Format: uuid
             */
            taskId: string;
        };
        /** RegisterRepositoryRequest */
        RegisterRepositoryRequest: {
            /** Path */
            path: string;
        };
        /** RepositoryResponse */
        RepositoryResponse: {
            /**
             * Createdat
             * Format: date-time
             */
            createdAt: string;
            /** Headrevision */
            headRevision: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Rootpath */
            rootPath: string;
            settings: components["schemas"]["RepositorySettingsResponse"];
        };
        /** RepositorySettingsRequest */
        RepositorySettingsRequest: {
            /** Compactionattemptlimit */
            compactionAttemptLimit?: number | null;
            /** Compactionmodel */
            compactionModel?: string | null;
            /** Compactionpromptversion */
            compactionPromptVersion?: string | null;
            /** Compactionthreshold */
            compactionThreshold?: number | null;
            /** Defaultcwd */
            defaultCwd?: string | null;
            /** Modelinputlimit */
            modelInputLimit?: number | null;
            /** Modeloutputreserve */
            modelOutputReserve?: number | null;
            /** Sandboximage */
            sandboxImage?: string | null;
            /** Sandboxnetwork */
            sandboxNetwork?: ("none" | "outbound") | null;
            /** Validationcommands */
            validationCommands?: components["schemas"]["ValidationCommandSettings"][] | null;
            /** Validationrepairlimit */
            validationRepairLimit?: number | null;
        };
        /** RepositorySettingsResponse */
        RepositorySettingsResponse: {
            /** Compactionattemptlimit */
            compactionAttemptLimit: number;
            /** Compactionmodel */
            compactionModel: string | null;
            /** Compactionpromptversion */
            compactionPromptVersion: string;
            /** Compactionthreshold */
            compactionThreshold: number;
            /** Defaultcwd */
            defaultCwd: string;
            /** Modelinputlimit */
            modelInputLimit: number;
            /** Modeloutputreserve */
            modelOutputReserve: number;
            /** Sandboximage */
            sandboxImage: string;
            /** Sandboxnetwork */
            sandboxNetwork: string;
            /** Schemaversion */
            schemaVersion: number;
            /** Validationcommands */
            validationCommands: components["schemas"]["ValidationCommandSettings"][];
            /** Validationrepairlimit */
            validationRepairLimit: number;
        };
        /** RepositoryTargetResponse */
        RepositoryTargetResponse: {
            /** Clean */
            clean: boolean;
            /** Currentref */
            currentRef: string | null;
            /** Headrevision */
            headRevision: string;
        };
        /** ResultRevisionResponse */
        ResultRevisionResponse: {
            /** Commitsha */
            commitSha: string;
            /**
             * Createdat
             * Format: date-time
             */
            createdAt: string;
            /** Createdby */
            createdBy: string;
            /**
             * Diffartifactid
             * Format: uuid
             */
            diffArtifactId: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Parentrevision */
            parentRevision: string;
            /** Previousresultrevisionid */
            previousResultRevisionId: string | null;
            /** Summary */
            summary: string;
            /**
             * Taskid
             * Format: uuid
             */
            taskId: string;
            /** Validationsnapshot */
            validationSnapshot: {
                [key: string]: unknown;
            };
        };
        /** StepTraceResponse */
        StepTraceResponse: {
            /** Calls */
            calls: components["schemas"]["ToolCallResponse"][];
            /**
             * Id
             * Format: uuid
             */
            id: string;
            manifest: components["schemas"]["ContextManifestSummary"] | null;
            /** Results */
            results: components["schemas"]["ToolResultResponse"][];
            /**
             * Runid
             * Format: uuid
             */
            runId: string;
            /** Status */
            status: string;
            /** Stepsequence */
            stepSequence: number;
        };
        /** SubmitMessageRequest */
        SubmitMessageRequest: {
            /** Text */
            text: string;
        };
        /** SubmittedRunResponse */
        SubmittedRunResponse: {
            /** Kind */
            kind: string;
            /**
             * Messageid
             * Format: uuid
             */
            messageId: string;
            /**
             * Runid
             * Format: uuid
             */
            runId: string;
            /** Runstatus */
            runStatus: string;
        };
        /** TaskEventEnvelope */
        TaskEventEnvelope: {
            /**
             * Createdat
             * Format: date-time
             */
            createdAt: string;
            /**
             * Eventid
             * Format: uuid
             */
            eventId: string;
            /** Payload */
            payload: {
                [key: string]: unknown;
            };
            /** Runid */
            runId: string | null;
            /** Runsequence */
            runSequence: number | null;
            /** Schemaversion */
            schemaVersion: number;
            /**
             * Taskid
             * Format: uuid
             */
            taskId: string;
            /** Tasksequence */
            taskSequence: number;
            /** Type */
            type: string;
        };
        /** TaskResponse */
        TaskResponse: {
            /** Baserevision */
            baseRevision: string | null;
            /**
             * Createdat
             * Format: date-time
             */
            createdAt: string;
            /** Failurecode */
            failureCode: string | null;
            /** Failuredetail */
            failureDetail: string | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Repositoryid
             * Format: uuid
             */
            repositoryId: string;
            /** Sourceref */
            sourceRef: string;
            /** Status */
            status: string;
            /**
             * Updatedat
             * Format: date-time
             */
            updatedAt: string;
            /** Workspacebaserevision */
            workspaceBaseRevision: string | null;
            /** Workspacegeneration */
            workspaceGeneration: number;
            /** Workspacepath */
            workspacePath: string;
        };
        /** TaskReviewResponse */
        TaskReviewResponse: {
            /** Claimedfiles */
            claimedFiles: string[];
            /** Completionsummary */
            completionSummary: string | null;
            /** Integrations */
            integrations: components["schemas"]["IntegrationResponse"][];
            /** Latestrunstatus */
            latestRunStatus: string | null;
            /** Resultrevisions */
            resultRevisions: components["schemas"]["ResultRevisionResponse"][];
            /** Validationattempts */
            validationAttempts: components["schemas"]["ValidationAttemptReviewResponse"][];
        };
        /** ToolCallResponse */
        ToolCallResponse: {
            /** Arguments */
            arguments: {
                [key: string]: unknown;
            };
            /** Callsequence */
            callSequence: number;
            /** Executionmode */
            executionMode: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
            /** Status */
            status: string;
        };
        /** ToolResultResponse */
        ToolResultResponse: {
            /** Artifactid */
            artifactId: string | null;
            /** Completionsequence */
            completionSequence: number;
            /** Displaytext */
            displayText: string;
            /** Errorcode */
            errorCode: string | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Result */
            result: {
                [key: string]: unknown;
            };
            /** Status */
            status: string;
            /**
             * Toolcallid
             * Format: uuid
             */
            toolCallId: string;
        };
        /** ValidationAttemptReviewResponse */
        ValidationAttemptReviewResponse: {
            /** Attemptnumber */
            attemptNumber: number;
            /** Commands */
            commands: components["schemas"]["ValidationCommandReviewResponse"][];
            /** Completedat */
            completedAt: string | null;
            /**
             * Createdat
             * Format: date-time
             */
            createdAt: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Runid
             * Format: uuid
             */
            runId: string;
            /** Status */
            status: string;
        };
        /** ValidationCommandReviewResponse */
        ValidationCommandReviewResponse: {
            /** Approvalid */
            approvalId: string | null;
            /** Artifactid */
            artifactId: string | null;
            /** Commandsequence */
            commandSequence: number;
            /** Completedat */
            completedAt: string | null;
            /**
             * Createdat
             * Format: date-time
             */
            createdAt: string;
            /** Exitcode */
            exitCode: number | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Status */
            status: string;
            /** Summary */
            summary: string;
            /** Toolcallid */
            toolCallId: string | null;
        };
        /** ValidationCommandSettings */
        ValidationCommandSettings: {
            /** Arguments */
            arguments: string[];
            /** Cwd */
            cwd: string;
            /** Environment */
            environment: {
                [key: string]: string;
            };
            /** Executable */
            executable: string;
            /** Image */
            image: string;
            limits: components["schemas"]["CommandLimitsSettings"];
            /**
             * Network
             * @enum {string}
             */
            network: "none" | "outbound";
            /** Reason */
            reason: string;
            /** Timeoutseconds */
            timeoutSeconds: number;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /** WorkspaceStateResponse */
        WorkspaceStateResponse: {
            /** Diff */
            diff: string;
            /** Difftruncated */
            diffTruncated: boolean;
            /** Status */
            status: string;
            /** Statustruncated */
            statusTruncated: boolean;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    decide_approval_api_approvals__approval_id__decision_post: {
        parameters: {
            query?: never;
            header?: {
                "Idempotency-Key"?: string | null;
            };
            path: {
                approval_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ApprovalDecisionRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApprovalResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_artifact_api_artifacts__artifact_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                artifact_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    bootstrap_api_auth_bootstrap_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BootstrapRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BootstrapResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    logout_api_auth_logout_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                crucible_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    resume_session_api_auth_session_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                crucible_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BootstrapResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    list_repositories_api_repositories_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RepositoryResponse"][];
                };
            };
        };
    };
    register_repository_api_repositories_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterRepositoryRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RepositoryResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_repository_settings_api_repositories__repository_id__settings_put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                repository_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RepositorySettingsRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RepositoryResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_repository_target_api_repositories__repository_id__target_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                repository_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RepositoryTargetResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_task_api_repositories__repository_id__tasks_post: {
        parameters: {
            query?: never;
            header?: {
                "Idempotency-Key"?: string | null;
            };
            path: {
                repository_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateTaskRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    integrate_result_api_result_revisions__result_revision_id__integrations_post: {
        parameters: {
            query?: never;
            header?: {
                "Idempotency-Key"?: string | null;
            };
            path: {
                result_revision_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["IntegrationTargetRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IntegrationResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    cancel_run_api_runs__run_id__cancel_post: {
        parameters: {
            query?: never;
            header?: {
                "Idempotency-Key"?: string | null;
            };
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CancelledRunResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_tasks_api_tasks_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskResponse"][];
                };
            };
        };
    };
    get_task_api_tasks__task_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                task_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    accept_task_api_tasks__task_id__acceptances_post: {
        parameters: {
            query?: never;
            header?: {
                "Idempotency-Key"?: string | null;
            };
            path: {
                task_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResultRevisionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_approvals_api_tasks__task_id__approvals_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                task_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApprovalResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    event_stream_api_tasks__task_id__events_get: {
        parameters: {
            query?: never;
            header?: {
                "Last-Event-ID"?: string | null;
            };
            path: {
                task_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_messages_api_tasks__task_id__messages_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                task_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MessageResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    submit_message_api_tasks__task_id__messages_post: {
        parameters: {
            query?: never;
            header?: {
                "Idempotency-Key"?: string | null;
            };
            path: {
                task_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SubmitMessageRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SubmittedRunResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_task_review_api_tasks__task_id__review_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                task_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskReviewResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_task_trace_api_tasks__task_id__trace_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                task_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StepTraceResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_workspace_state_api_tasks__task_id__workspace_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                task_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkspaceStateResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
